[package]
name = "rustup"
version = "0.1.0"
authors = ["Kevin Darlington <kevin@outroot.com>"]

[dependencies]
hyper = "0.6.12"
env_logger = "*"
toml = "0.1"
time = "*"
rustbar = "*"
rustc-serialize = "*"
